# This is a basic workflow to help you get started with Actions

name: master-ci

permissions: write-all

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2
      - name: Install mdbook
        run: |
          cargo install mdbook
      - name: Install TOC on pages
        run: |
          cargo install mdbook-pagetoc
      - name: Build static artifacts
        run: |
          mdbook build
      - name: Generate .nojekyll
        run: |
          touch book/.nojekyll
      - name: Delete Production Branch
        uses: dawidd6/action-delete-branch@v3
        with:
          branches: upstream-release
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Github Production branch
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: book
          branch: upstream-release
          clean: true
